sudo: required
dist: trusty
before_install:
  - wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
  - wget https://swift.org/builds/swift-4.0-branch/ubuntu1404/swift-4.0-DEVELOPMENT-SNAPSHOT-2017-08-04-a/swift-4.0-DEVELOPMENT-SNAPSHOT-2017-08-04-a-ubuntu14.04.tar.gz
  - tar xzf swift-4.0-DEVELOPMENT-SNAPSHOT-2017-08-04-a-ubuntu14.04.tar.gz
  - export PATH=${PWD}/swift-4.0-DEVELOPMENT-SNAPSHOT-2017-08-04-a-ubuntu14.04/usr/bin:"${PATH}"
script:
  - swift build && swift test
