branches:
  only:
    - master
    - develop
    - /^hotfix.*$/
    - /^feature.*$/

matrix:
  include:
    - os: linux
      install: 
        - gem install bundler
        - bundler install
      before_script:
        - bundle exec danger
      before_install:
        - wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
        - wget -q https://swift.org/builds/development/ubuntu1404/swift-DEVELOPMENT-SNAPSHOT-2017-09-04-a/swift-DEVELOPMENT-SNAPSHOT-2017-09-04-a-ubuntu14.04.tar.gz
        - tar xzf swift-DEVELOPMENT-SNAPSHOT-2017-09-04-a-ubuntu14.04.tar.gz
        - export PATH=${PWD}/swift-DEVELOPMENT-SNAPSHOT-2017-09-04-a-ubuntu14.04/usr/bin:"${PATH}"
      script:
        - make travis
    - os: osx
      osx_image: xcode9
      sudo: required
      env: CODECOV_TOKEN=$CODECOV_TOKEN
      script:
        - make travisosx
